ifeq ($(CONFIG_OPLUS_SM7250R_CHARGER),y)
	obj-y	+= oplus_da9313.o
	obj-y   += oplus_battery_msm7250_R.o
	obj-y	+= oplus_mp2650.o
	obj-y   += oplus_usbtemp.o
endif

obj-y   += s2asl01_switching.o
obj-y   += oplus_switching.o
obj-y   += oplus_short_ic.o
