name: NeverSettle Kernel Compiler
on:
  workflow_dispatch:
      inputs:
         Buildtype:
             description: 'Build Type'
             required: true
             default: 'TEST'
         Changelog:
             description: 'Build Changelog'
             required: true
             default: '* No Changelog provided by the developer'
  
env:
  CHANGELOG: ${{ github.event.inputs.Changelog }}
  BUILDTYPE: ${{ github.event.inputs.Buildtype }}
jobs:
  NSK_CI:
    runs-on: ubuntu-22.04
    steps:
       - name: Install packages
         run: |
            sudo apt-get update
            sudo apt-get -y install mkisofs git python2 bc cpio python3 python-is-python3 device-tree-compiler wget jq
       - name: Initiate cloning
         run: |
            cd ~
            git clone https://github.com/pratikkabra143/android_kernel_oneplus_avicii -b $GITHUB_REF_NAME --depth=1 kernel
            cd kernel
            sed -i 's/ccflags-y += $(subst $(srctree),source,$(INCS))/ccflags-y += $(INCS)/g' drivers/staging/qcacld-3.0/Kbuild
       - name: Build NS Kernel
         run: |
            cd ~/kernel
            python build.py
       - name: Upload Kernel Build Artifacts
         if: always()
         uses: actions/upload-artifact@v7
         with:
           name: NeverSettle-Kernel-${{ github.event.inputs.Buildtype }}-Artifacts
           path: |
             /home/runner/*.zip
             /home/runner/*.apk
             /home/runner/*.txt
             /home/runner/kernel/error.log
           if-no-files-found: warn
