name: NeverSettle Kernel Compiler
on:
  workflow_dispatch:
      inputs:
         Buildtype:
             description: 'Build Type'
             required: true
             default: 'TEST'
         Changelog:
             description: 'Build Changelog'
             required: true
             default: '* No Changelog provided by the developer'

env:
  TOKEN: ${{ secrets.TG_BOT_TOKEN }}
  CHATID: ${{ secrets.TG_CHAT_ID }}
  CHATIDTEST: ${{ secrets.TG_CHAT_ID_TEST }}
  CHANGELOG: ${{ github.event.inputs.Changelog }}
  BUILDTYPE: ${{ github.event.inputs.Buildtype }}
jobs:
  NSK_CI:
    runs-on: ubuntu-22.04
    steps:
       - name: Install packages
         run: |
            sudo apt-get update
            sudo apt-get -y install mkisofs git bc cpio python2 python3 python-is-python3 device-tree-compiler wget jq
       - name: Initiate cloning
         run: |
            cd ~
            git clone https://github.com/sreeshankark/android_kernel_oneplus_avicii -b $GITHUB_REF_NAME --depth=1 kernel
       - name: Build NS Kernel
         run: |
            cd ~/kernel
            python scripts/build_kernel.py
